### ISSUE TITLE
Port more video control settings (Undo Seek + Seek to specific time)

### ISSUE THREAD

**Issue by Reddnek** [Reddnek/syncplay-android#23]
***Undo Seek***: There should be no more "Oups". When a user mistakingly seeks, he should be able to revert the action.

***Seek to specific time***: Ability to enter a specific time to seek to without looking for it with the seek bar.

**Comment by Et0h** [comment]
You're free to port the offset feature but be aware that Syncplay PC consider it a deprecated feature.

Offset made some sense as a feature when Syncplay was first released in around 2012 and was focused on just syncing one file. At that time opening and ending files were sometimes stored externally and some players didn't handle that properly meaning the was a fixed knowable offset to apply to fix the playback.

Now we have shared playlists it is not intuitive in terms of how it's supposed to be compatible with automatic file switching and whether the offset should apply to all videos or just the current one, etc.

**Comment by chromaticnoob** [comment]
@Et0h I was wondering what the offset would be for other than syncing videos that appear to be a bit different (such as a movie from a BluRay release, compared to a movie from a WEB-DL release) but even so it didn't make much sense to me. Now that I know what it was supposed to be a solution for, it only makes sense to deprecate it. If so, deprecation means that it's no longer recommended for use. Coding-wise it would indeed complicate things,  I believe that I should focus on other important features to port since my end goal is to make the perfect client that has the same mirrorcopy functionality as Syncplay PC.

**Comment by Et0h** [comment]
Syncplay/syncplay#435 provides a discussion of this feature and its deprecation. At least one group of users uses the feature "all the time" despite the complexities so you could still implement the feature for such groups if you want. However there is no need to cater for every use case, so you could decide to make it a low priority.

**Comment by chromaticnoob** [comment]
It is still possible to implement the feature, and I believe that the announced video position would not change even after setting the offset, correct ? If so, despite it being a bit complicated to implement, it can be added last after porting all non-deprecated features. I will end up bored and idle-handed anyhoo. I separated it the issue as a feature port of low priority.

Btw, I stumbled upon something called "room persistence", I might have had a faint idea of what it is, but I guess it's just server-side ?

**Comment by Et0h** [comment]
> It is still possible to implement the feature, and I believe that the announced video position would not change even after setting the offset, correct ?

If I recall correctly (and its been a while since I've looked at that code in detail) the announced video position adjusts for the offset. There is nothing in the protocol to state that the position is having an offset applied to it.

> Btw, I stumbled upon something called "room persistence", I might have had a faint idea of what it is, but I guess it's just server-side ?

Room persistence allows for room playlist information to be retained on private servers even when nobody is in a room.

The related feature called room permanence allows for a list of rooms to be specified on the server which will then always be listed in the list of rooms (who is playing what) even when nobody is in them (especially useful for managed rooms).

While both of these features are server side, they also have the effect of allowing rooms to appear in the list of who is playing what that don't have any actual users in them. The Syncplay protocol/client was never designed to handle empty rooms. To make the feature backwards compatible with older clients we therefore have to use blank dummy users to populate such rooms. Newer clients can detect the room is actually empty and there is a GUI options to hide empty rooms from the list of who is playing what. That's useful for if you have many many persistent rooms which is a use case we've heard of although it's probably not a common use case.

**Comment by Reddnek** [comment]
Added more seek features in the latest version [0.11.0](https://github.com/Reddnek/syncplay-android/releases/tag/v0.11.0).
