### ISSUE TITLE
package renamed again?

### ISSUE THREAD

**Issue by IzzySoft** [Reddnek/syncplay-android#35]
Do you plan to rename the app every month? It originally started as `com.gintoki.syncplay`, got renamed to `com.chromaticnoob.syncplay` at 2022-07-10, and now (just a month later) was again renamed to `com.reddnek.syncplay`. Each rename means it becomes a different app. There will be no update notifications (or updates at all) for the currently installed app, users need to uninstall and reinstall. Thus, keeping renaming it every month means manually checking and switching every month – which I doubt is in the best interest of your users.

So: Will this be the last time, or do you plan to continue the renaming? Because as nice as the app is (and thanks for making it available freely and under a FOSS license!), next time I'll rather drop it.

Apologies for the rant, but this is rather unnerving. :cry:

**Comment by IzzySoft** [comment]
PS: besides, the APK attached to `releases/` is compiled for debugging (has the `application-debuggable` flag) – probably unintentionally.

**Comment by Reddnek** [comment]
The app started out as a random project back in 2020, I had the ```com.gintoki.syncplay``` package name and I didn't even notice that was the package name when I first deployed it to GitHub. However, my GitHub name was 'chromaticnoob' which required me to change the package name to follow with it. 

A month ago, I decided to go back to a name that I widely used along my developer career across a lot of forums and everything, so I will stick to Reddnek. That, of course, also required me to change the package name.

As unnerving as this is, this should be the last time the package name is changed, since the app is going to be deployed to the Play Store soon. You can just think of it as a 'name nomad' kind of journey, had to settle for one.

And yes, I released the APK for debugging by mistake, just noticed that this morning. For now, that should be harmless since the app is completely usable even with the debug flag. Thanks for putting that to my attention !

**Comment by Reddnek** [comment]
The app started out as a random project back in 2020, I had the com.gintoki.syncplay package name and I didn't even notice that was the package name when I first deployed it to GitHub. However, my GitHub name was 'chromaticnoob' which required me to change the package name to follow with it.

A month ago, I decided to go back to a name that I widely used along my developer career across a lot of forums and everything, so I will stick to Reddnek. That, of course, also required me to change the package name.

As unnerving as this is, this should be the last time the package name is changed, since the app is going to be deployed to the Play Store soon. You can just think of it as a 'name nomad' kind of journey, had to settle for one.

I am fully aware of the consequences of making the app different every release, not only does it cause a rather unlikeable installation impression and UX, but that also means the users have to re-configure the app all over again, meaning that media directories, settings and preferences are all deleted and gone, which is not for the best interest of anyone even myself.

And yes, I released the APK for debugging by mistake, just noticed that this morning. For now, that should be harmless since the app is completely usable even with the debug flag.

**Comment by IzzySoft** [comment]
Thanks a lot, @Reddnek – then all is fine! For some additional background: your app is [listed in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.reddnek.syncplay). In order for the user to be notified about updates it's important the `applicationId` does not change – else it makes no sense to put the app into such a repo :wink: Not that this "stabilized", you might wish to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there from your Readme :smile:

Btw: The package name is not bound to your Github name in any way – though it cannot hurt to have it match. AFAIK there's a guideline that ideally it should go by a domain you own (`reddnek.com` by your current package name), but there are no strict (or even enforced) rules on this.

**Comment by Reddnek** [comment]
@IzzySoft It's such a pleasure to see the app hosted on another repo. F-Droid kind of complicated the deployment process for me due to the external FFmpeg extension that is bundled with the app, and therefore decided to deploy the app to Play store for ease of updates. However, seems like your repo also supports updates, which is great. I believe the package renaming was rather uncalled-for and it complicated the hosting process. However, since the app is hosted on your repo and will be soon on Play store too, then the package name should remain the same for years to come. I just didn't want anyone to confuse the developer of the app with someone else, for example, downloading an app with the package name ```com.chromaticnoob``` from someone named ```Reddnek``` can only mean that the latter is not really the original developer.

And thank you very much on the badge, I will be adding it to the Readme at once.

**Comment by IzzySoft** [comment]
Yes, indeed having the two match gives additional confidence. And F-Droid might look complicated at times, though solutions exist for most things (e.g. there's an `FFmpeg` srclib available at F-Droid which you might use if you target a listing there – provided it matches your needs: it's taken from `git://source.ffmpeg.org/ffmpeg`, and there's also `FFMPEG-Java` taken from `https://github.com/guardianproject/android-ffmpeg-java.git`).

Updates via my repo might be even faster than PlayStore's approval process: within 24h of your tagging a new release and attaching the APK, it will be available in my repo; provided the package name did not change again :stuck_out_tongue_winking_eye:). Thanks to your adding the badge so prominently, your users can easily follow up and install from there, using their favorite [F-Droid client](https://android.izzysoft.de/applists/category/named/apps_markets#group_1181).

So let's have an ongoing fantastic team-work on this :smiley:

**Comment by Reddnek** [comment]
@IzzySoft The FFmpeg extension that is bundled with the app is rather 'lite', in a way that it only supports audio, and it is different since it is buitl by a special ExoPlayer script to support certain formats only. For that, they required me to actually provide a build script that mimics the entire process (which was already a hurdle). Honestly, I found it rather more tiresome than it is worth. I prefer it be hosted on a repo that doesn't impose such guidelines and requirements, in which case your repo is definitely better for me. 

The approval window being shorter than 24h is already magnificent ! I will try to fight my urge not to change the package name again so all things go smoothly. I will also adjust the Readme very soon in the future to make it easier as well as clarify the download process via the repo. Team on!

**Comment by IzzySoft** [comment]
@Reddnek Thanks! And of course your app is welcome to stay. You might at a point wish to add [Fastlane Structures](https://gitlab.com/-/snippets/1895688) to your apps' repos (I can provide you with a starter package for both via PR if you wish) so you can also control how your apps are presented (description, screenshots etc).

**Comment by IzzySoft** [comment]
> I will try to fight my urge not to change the package name again so all things go smoothly.

@Reddnek When will you stop renaming the package? That's now the 3rd time in just 6 months. This not only causes a bunch of extra work on my end, but also forces your users to uninstall and re-install the app each time. To be honest, I'm tired of cleaning up every time.

This is the last time I follow your rename, but without keeping the previous version for an overlap. Next time I might simply drop it. I run my repo for more than 6 years now and your app is the only one behaving like this; a few had a single rename, but none 3 within a year – if it continues this way, it's rather messy for all involved.

Btw: Switching to the new package name also means the link in your Readme will be broken with the next sync, so please remember to update it then.

**Comment by Reddnek** [comment]
@IzzySoft My my, silly me, this was actually not intended this time. I felt I forgot something before posting the release. I was keeping the old and new APKs simultaneously installed since I was revamping the whole thing but that was only for development purposes. I have no plan to rename it anytime in the future. I will fix that when I get home.

**Comment by Reddnek** [comment]
@IzzySoft The package name is now fixed. Apologies for the inconvenience and the extra work.

**Comment by IzzySoft** [comment]
Thanks, chenge rolled back here (effective with the next sync). As APK size increased to beyond 20 MB, my repo will now only hold the latest version (as 2 APKs would exceed the per-app limit) of 30 MB).

**Comment by Reddnek** [comment]
@IzzySoft You're going above and beyond for this, much appreciated.

**Comment by IzzySoft** [comment]
Thanks! "Going beyond" I'd ask you to consider per-ABI builds – and then would pick one of the ARM builds (either armeabi or arm64, you say). They'd be much smaller then (currently around 10 MB each), so I could keep multiple versions again. But then you must promise to stick to the packageName – and I'd refuse any renaming in the future, waiting for you to fix the name back :wink:

**Comment by Reddnek** [comment]
@IzzySoft 
I have already updated the '0.11.0' release to '0.11.1' as I felt like people would miss the changelog if I drafted a new release. The attached APK should have the old package name, promise it won't be changed again ;) 

As for the app size, the reason why it has grown so much is because of the absence of code obfuscation (R8/Minifying). If I enabled said option, it would cause some crashes so by the next release it should have around 10 MBs max.

**Comment by IzzySoft** [comment]
You can enable minification without obfuscation, which should help some. See eg. [Minify android app but do not obfuscate it](https://stackoverflow.com/q/35853593/2533433). If size is reduced below 15 MB, just drop me a note and I enable keeping multiple versions again.

**Comment by Reddnek** [comment]
@IzzySoft Much appreciated! I will definitely do that.

**Comment by IzzySoft** [comment]
I've got a [small collection of hints](https://gitlab.com/-/snippets/1896503) should you need more :wink:
