### ISSUE TITLE
Landscape for main screen in tablets

### ISSUE THREAD

**Issue by DarremMolko** [Reddnek/syncplay-android#39]
Hi! First than nothing congrats for publishing the app to the Google Play Store, I hope it gains the recognition it deserves. 
And now, going to what concerns us. This is not a big deal but I mostly use my tablet in landscape and the app main screen seems to be forced into portrait which makes it a little uncomfortable. I hope you could improve this in the next release.
Thank you in advance.

**Comment by Reddnek** [comment]
I will fix that in the next update. Thank you for your feedback !

**Comment by Reddnek** [comment]
@DarremMolko Fixed as of version [0.10.0](https://github.com/Reddnek/syncplay-android/releases/tag/v0.10.0)
Test it out and let me know.

**Comment by DarremMolko** [comment]
It rotates correctly now, thank you. This is not related at all (or maybe it is because of my tablet's screen size) but the soft coded subtitles in my videos appears too small. Do you plan adding subtitles customization?
![Screenshot_20221027-083456](https://user-images.githubusercontent.com/70179709/198274946-ed43aef5-6bcc-433c-a88f-7ebe13c8b73a.png)

**Comment by Reddnek** [comment]
@DarremMolko This can be due to two things: Very large screen size (Subtitle size is fixed and not relative) or the subtitle is of SSA/ASS extension and it contains very small subtitle size

The app has an option to adjust subtitle size from inside the room (in-room settings) as you can see in the following screenshot (Some users have reported that the adjustment wont take effect until you leave the room and enter again), so try changing it, leaving the room, and entering again. That should fix it.

![Screenshot_2022-10-27-13-33-32-71_e8c13c460341f72b964618acedd5597a.jpg](https://user-images.githubusercontent.com/72363167/198286151-7b5e6a4b-b716-406f-a972-d8cc6f11a1d9.jpg)

**Comment by DarremMolko** [comment]
> @DarremMolko This can be due to two things: Very large screen size (Subtitle size is fixed and not relative) or the subtitle is of SSA/ASS extension and it contains very small subtitle size
> 
> The app has an option to adjust subtitle size from inside the room (in-room settings) as you can see in the following screenshot (Some users have reported that the adjustment wont take effect until you leave the room and enter again), so try changing it, leaving the room, and entering again. That should fix it.
> 
> ![Screenshot_2022-10-27-13-33-32-71_e8c13c460341f72b964618acedd5597a.jpg](https://user-images.githubusercontent.com/72363167/198286151-7b5e6a4b-b716-406f-a972-d8cc6f11a1d9.jpg)

That indeed worked and I didn't have to leave and enter the room again for it to take effect. But the "solo player mode" seems to lack the in-room settings, should I open another issue regarding that?

**Comment by Reddnek** [comment]
@DarremMolko Oh yes, given the fact that 99% of the in-room settings have something to do with the online room. Open a new issue, I will make sure to include that in the next version.
