### ISSUE TITLE
No display of video.

### ISSUE THREAD

**Issue by rammedisoft** [Reddnek/syncplay-android#44]
The app installs well, runs OK, slightly difficult to set the the file list.
However on running, only the audio runs, synch with the server. 
But video file does not display on the app.
Am I missing something?
Synchronisation indeed but only audio!

**Comment by Reddnek** [comment]
@rammedisoft, On all of my test devices, I haven't confronted this issue so it may be device-specific or specific to the Android version you're running. I need more information to narrow down the cause. First of all, try an older version (such as [v0.8.0](https://github.com/Reddnek/syncplay-android/releases/tag/v0.8.0)) and let me know if the issue is still there.

Also, try to test the issue in Solo (Video-only) Player, as well as different video formats.

Whether the issue persists or not, provide me with the following information:
- Device Model (Manufacturer and Model Number).
- Android Version.
- Type of video you're trying to play (Some formats aren't supported).

**Comment by rammedisoft** [comment]
Sorry for raising this issue before checking further. 
After I posted this issue, I came across different posts, in this section, esp. the one labelled "Video player requests #38"
I found out the limitations of Google Exo player. 
Then I checked with different video files. It worked. I checked the media info using FormatFactory and here is the abridged details.

Successful video
General
Complete name                            : da1.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
Overall bit rate                         : 348 kb/s
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4
Format settings                          : CABAC / 3 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 3 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Bit rate                                 : 214 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 24.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.004
Stream size                              : 140 MiB (62%)
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
Codec configuration box                  : avcC

Failed video had different parameters.
[Failed Video.txt](https://github.com/Reddnek/syncplay-android/files/10003341/Failed.Video.txt)

I request you to put the list of various video formats supported by your App or give link to the Exoplayer website in the description of your App.

**Comment by Reddnek** [comment]
@rammedisoft I am glad to hear that you got the app to work. There is no Android device that has built-in support for ```mp1v```format at the moment

Exoplayer either uses the device's hardware codecs or its integrated software codecs (which support all audio formats, but a limited list of video formats). I should indeed cite this piece of information in the readme in order to not confuse other people.

I am planning to release Syncplay with a much more powerful player in the future, which would give support to a myriad of formats.
